### ISSUE TITLE
Feature Request: Documentation (Installing + help)

### ISSUE THREAD

**Issue by marteaurouge** [Muffindrake/strimgo#1]
Nice work!
some lines to help people how to install go and how to launch the script would be appreciated!

**Comment by Muffindrake** [comment]
I've added an installation description with links to `git` and `go` tools, as well as command line instructions to get it running. Also added a note for linux users that may want to use the Rust port instead.

If there's anything missing, let me know.

**Comment by marteaurouge** [comment]
wow thanks! sounds good, i'll test it today :)
